"""Generate Bilibili video descriptions with LLM-powered fun sentences.

Produces Chinese-language descriptions that mention the video is transported
from YouTube, include the YouTube view count and link, and lead with a
short witty sentence generated by the LLM.

Also provides title translation (English -> Chinese) for the upload pipeline.
"""
import json
import logging
from typing import Any, Dict, Optional, Protocol, runtime_checkable

logger = logging.getLogger(__name__)


@runtime_checkable
class _LLMBackend(Protocol):
    def chat(self, messages: list[dict[str, str]], json_schema=None) -> str: ...


def format_view_count(views: int) -> str:
    """Format a view count for Chinese display.

    >= 1亿 (100M) → "X.X亿次观看"
    >= 1万 (10K)  → "X.X万次观看"
    otherwise     → "X次观看"
    """
    if views >= 1_0000_0000:
        value = views / 1_0000_0000
        if value == int(value):
            return f"{int(value)}亿次观看"
        return f"{value:.1f}亿次观看"
    if views >= 1_0000:
        value = views / 1_0000
        if value == int(value):
            return f"{int(value)}万次观看"
        return f"{value:.1f}万次观看"
    return f"{views}次观看"


def _build_prompt(video_info: Dict[str, Any]) -> list[dict[str, str]]:
    title = video_info.get("title", "Unknown")
    channel = video_info.get("channel", "Unknown")
    views = video_info.get("view_count", 0)

    return [
        {
            "role": "system",
            "content": (
                "你是一个B站视频简介撰写助手。"
                "用户会给你一个从YouTube搬运的视频的信息。"
                "请用中文写一句简短、有趣、吸引人的话来介绍这个视频的内容。"
                "要求：只输出一句话，不要加引号，不要加标点以外的任何格式，不要重复视频标题。"
            ),
        },
        {
            "role": "user",
            "content": (
                f"视频标题：{title}\n"
                f"频道：{channel}\n"
                f"YouTube播放量：{views:,}\n"
                f"\n请写一句有趣的中文介绍语。"
            ),
        },
    ]


def _build_template(video_info: Dict[str, Any]) -> str:
    views = video_info.get("view_count", 0)
    video_id = video_info.get("video_id", "")
    view_str = format_view_count(views)
    yt_link = f"https://www.youtube.com/watch?v={video_id}" if video_id else ""

    lines = [
        "",
        "本视频搬运自YouTube",
        f"原视频播放量：{view_str}",
    ]
    if yt_link:
        lines.append(f"原视频链接：{yt_link}")
    return "\n".join(lines)


def fallback_description(video_info: Dict[str, Any]) -> str:
    """Template-only description (no LLM sentence)."""
    title = video_info.get("title", "")
    template = _build_template(video_info)
    if title:
        return f"【{title}】{template}"
    return template.lstrip("\n")


def generate_description(
    backend: Optional[_LLMBackend],
    video_info: Dict[str, Any],
) -> str:
    """Generate a full Bilibili description with an LLM-written fun sentence.

    Falls back to template-only if backend is None or LLM call fails.
    """
    template = _build_template(video_info)

    if backend is None:
        return fallback_description(video_info)

    try:
        messages = _build_prompt(video_info)
        response = backend.chat(messages)
        fun_sentence = response.strip().strip('"').strip("'").strip()

        if not fun_sentence or len(fun_sentence) > 200:
            logger.warning("LLM returned empty or too-long sentence, using fallback")
            return fallback_description(video_info)

        return fun_sentence + template
    except Exception as e:
        logger.warning("LLM description generation failed: %s", e)
        return fallback_description(video_info)


# ── Title translation ────────────────────────────────────────────────

_TRANSLATE_TITLE_PROMPT = """\
Translate the following English YouTube video title into Chinese for a Bilibili audience.

Title: "{title}"

Rules:
- Translate naturally for a Chinese audience
- Keep proper nouns (names, brands, places) in their commonly used Chinese form or keep them in English
- Stay concise — Bilibili titles should be short and catchy
- If the title is already in Chinese, return it as-is
- Do NOT add extra commentary or explanation

Respond with JSON:
{{"chinese_title": "<translated title>"}}"""


def translate_title(backend: Optional[_LLMBackend], english_title: str) -> str:
    """Translate an English video title to Chinese via LLM.

    Falls back to the original English title on any failure.
    """
    if backend is None or not english_title:
        return english_title
    try:
        prompt = _TRANSLATE_TITLE_PROMPT.format(title=english_title)
        response = backend.chat(
            [
                {"role": "system", "content": "你是一个专业的视频标题翻译助手。"},
                {"role": "user", "content": prompt},
            ],
            json_schema={
                "type": "object",
                "properties": {"chinese_title": {"type": "string"}},
                "required": ["chinese_title"],
            },
        )
        data = json.loads(response)
        chinese = data.get("chinese_title", "").strip()
        if chinese:
            logger.info("Translated title: '%s' -> '%s'", english_title, chinese)
            return chinese
        return english_title
    except Exception as e:
        logger.warning("Title translation failed: %s", e)
        return english_title
